Getting rid of episodes with activity and fixing episode counts
lkorczowski/Tinnitus-n-Sleep pull request #106
Opened 2020-11-13 14:47 UTC by RobinGuillard

- [X] Suppresses the episodes of MEMA/bruxism that overlap with unvalid labels from valid labels (OMA, wake, impedance checking issue). On the following image, it means keeping the first episode flageed "2" and getting rid of the 2nd.
![image](https://user-images.githubusercontent.com/14861704/99084771-a9a7d400-25c7-11eb-8dec-ade1ecadcad9.png)

- [X] Fixed issue that was present and now fixed on the decounting of the number of episodes:
![image](https://user-images.githubusercontent.com/14861704/99112939-bc81cf00-25ee-11eb-8862-b3dff02bbdab.png)

- [X] Added the "labels_1s_extension" in utils function that enables to enlarge/extend OMA events

- [x] recomputed all results

2020-11-16 14:57 UTC, RobinGuillard commented
Tried to run all subjects on Bruxism + MEMA and got the following error for 3NS01

```
3NS01_cohort2.edf (sleep labels 

WARNING:tinnsleep.data:non uniform interval (count: [(13.0, 1), (22.0, 1), (30.0, 1425)]), taking median: 30.0
WARNING:tinnsleep.data:start time, file: 22:13:38 labels: 25/08/2020 22:13:38

, loaded) preprocess... Bruxism(done) MEMA(done) DONE (44.34s) report... Bruxism(

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\compute_results.py in <module>
    263                                                       delim=delim, n_adaptive=n_adaptive_bruxism, log=log,
    264                                                       generate_report=generate_bruxism_report,
--> 265                                                       sleep_labels=sleep_labels_bruxism)
    266                     print(f"done)", end=" ")
    267                 else:

~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\reports.py in reporting(epochs, valid_labels, THR_classif, time_interval, delim, n_adaptive, log, generate_report, sleep_labels, valid_sleep_stages)
    313         # -----------------Classification Forward ------------------------------------------------
    314         pipeline = AmplitudeThresholding(abs_threshold=THR[0], rel_threshold=THR[1], n_adaptive=abs(n_adaptive))
--> 315         labels = pipeline.fit_predict(X)
    316         if n_adaptive < -1:
    317             # -----------------Classification backward ---------------------------------------

~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\classification.py in fit_predict(self, X, y)
    142     def fit_predict(self, X, y=[]):
    143         """Fit and predict in one function."""
--> 144         self.fit(X, y)
    145         return self.predict(X)

~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\classification.py in fit(self, X, y, sample_weight)
     73 
     74         # Check that X and y have correct shape
---> 75         X = check_array(X)
     76 
     77         self.center_ = np.average(X, axis=0, weights=sample_weight)

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    548                              " minimum of %d is required%s."
    549                              % (n_samples, array.shape, ensure_min_samples,
--> 550                                 context))
    551 
    552     if ensure_min_features > 0 and array.ndim == 2:

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.
```

2020-11-16 20:55 UTC, lkorczowski commented
> Tried to run all subjects on Bruxism + MEMA and got the following error for 3NS01
> 
> ```
> 3NS01_cohort2.edf (sleep labels 
> 
> WARNING:tinnsleep.data:non uniform interval (count: [(13.0, 1), (22.0, 1), (30.0, 1425)]), taking median: 30.0
> WARNING:tinnsleep.data:start time, file: 22:13:38 labels: 25/08/2020 22:13:38
> 
> , loaded) preprocess... Bruxism(done) MEMA(done) DONE (44.34s) report... Bruxism(
> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> ~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\compute_results.py in <module>
>     263                                                       delim=delim, n_adaptive=n_adaptive_bruxism, log=log,
>     264                                                       generate_report=generate_bruxism_report,
> --> 265                                                       sleep_labels=sleep_labels_bruxism)
>     266                     print(f"done)", end=" ")
>     267                 else:
> 
> ~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\reports.py in reporting(epochs, valid_labels, THR_classif, time_interval, delim, n_adaptive, log, generate_report, sleep_labels, valid_sleep_stages)
>     313         # -----------------Classification Forward ------------------------------------------------
>     314         pipeline = AmplitudeThresholding(abs_threshold=THR[0], rel_threshold=THR[1], n_adaptive=abs(n_adaptive))
> --> 315         labels = pipeline.fit_predict(X)
>     316         if n_adaptive < -1:
>     317             # -----------------Classification backward ---------------------------------------
> 
> ~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\classification.py in fit_predict(self, X, y)
>     142     def fit_predict(self, X, y=[]):
>     143         """Fit and predict in one function."""
> --> 144         self.fit(X, y)
>     145         return self.predict(X)
> 
> ~\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\classification.py in fit(self, X, y, sample_weight)
>      73 
>      74         # Check that X and y have correct shape
> ---> 75         X = check_array(X)
>      76 
>      77         self.center_ = np.average(X, axis=0, weights=sample_weight)
> 
> ~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
>     548                              " minimum of %d is required%s."
>     549                              % (n_samples, array.shape, ensure_min_samples,
> --> 550                                 context))
>     551 
>     552     if ensure_min_features > 0 and array.ndim == 2:
> 
> ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.
> ```

`check_array` did the job well. X is an empty array of shape (0,1)

I will check it out tomorrow. 

Meanwhile : #107 fix the issue of having to remove any file from the analysis.

2020-11-18 12:42 UTC, lkorczowski requested changes
Here are some keys issues:
- [x] bad naming for variable and functions (mostly fixed by commit)
- [x] issue with valid_labels in generate_report: `np.invert` could have been a problem. This issue is not completely fix. I feel that something could be wrong and we need more pytesting I think.
- [ ] NB check: not done yet. Will do after everything else.

Please read the comment. If the comment is noted "obsolete" it is because I try to fix.

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/reports.py
> +def generate_bruxism_report(classif, time_interval, delim, valid_labels, min_burst_joining=3, sleep_labels=None):
valid_labels shouldn't be a mandatory parameters (I'm dealing with it).

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/reports.py
> +            new_ep_list.append(ep)
smart !

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/utils.py
> +        labels = labels.tolist()
nice catch

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/utils.py
>              labels.insert(i, False)  # inserting False (neutral) values in the labels array where they were deleted
now that I think about it, the use of `np.mean` is not great.

Also, the insert in labels shouldnt work as expected (insert will shift all index so "i" is not the good reference). I need to check how it has been pytested.

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/utils.py
> +    return new_l
omg. I will give you the medal of "master of lists". I need to double check carefully that :/ 

XD

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/utils.py
> +    return l
OK got it !
 I believe the aim is to expend the artifacts tags. A description would be great.

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/utils.py
> +    return new_l
ok, so I reviewed that code and I see less and less its purpose, so my comment about using "+" instead.

Please explain the use case.

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/utils.py
> +    """
description and use case missing

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/reports.py
> +    classif_good_length = fuse_with_classif_result(np.invert(valid_labels),
Carefull if you use `np.invert` as:
```
np.invert([1,0])  # matrix inversion
> array([-2, -1]) 
```

fix:
```
np.invert(np.array([0,1])==1)
> array([ True, False])
```

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/reports.py
> +    classif_good_length = fuse_with_classif_result(np.invert(valid_labels),
it is done. (see new version)

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/reports.py
> +    classif_good_length = fuse_with_classif_result(np.invert(valid_labels),
same problem (dealt with, see new lines)

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/utils.py
> +        labels = labels.tolist()
but the fact that it uses list only is suboptimal (numpy is almost always better)

I'm creating an issue to refactor this funciton

2020-11-18 12:42 UTC, lkorczowski commented on tinnsleep/reports.py
> +def generate_bruxism_report(classif, time_interval, delim, valid_labels, min_burst_joining=3, sleep_labels=None):
done

2020-11-18 12:50 UTC, lkorczowski commented
@RobinGuillard : PR done. We should merge to master asap for fixing other stuff in smaller batch.
Note: I didn't check the NB, should I ?

2020-11-18 13:24 UTC, RobinGuillard commented on tinnsleep/utils.py
> +    return new_l
I believe you found your answer just below!

2020-11-18 13:24 UTC, RobinGuillard commented on tinnsleep/utils.py
> +    return l
Yep!
Ok for the description...

2020-11-18 13:25 UTC, RobinGuillard commented on tinnsleep/utils.py
> +    """
Ok ok

2020-11-18 13:26 UTC, RobinGuillard commented on tinnsleep/reports.py
> +    classif_good_length = fuse_with_classif_result(np.invert(valid_labels),
Great!

2020-11-18 14:12 UTC, merged