completing reports for laterality
lkorczowski/Tinnitus-n-Sleep pull request #110
Opened 2020-11-19 21:15 UTC by RobinGuillard

- [X] added new reports in results_MEMA : file+_left et file+_both (for both ears)
- [X] resmed files are now treated differently than others and are saved in file+left reports.
- [ ] refactoring of NB to deal with laterality

2020-11-20 10:10 UTC, lkorczowski requested changes
- data_info have two version: please merge both
- there is an issue for not being able to tell if it was right/left ear for subjects with only one MEMA electrode. I proposed a fix.

2020-11-20 10:10 UTC, lkorczowski commented on notebooks/Middle_ear_Inter_subject_analysis.ipynb
> +    "data_info = pd.read_csv(info_file, sep=\";\").query('mema == 1 & included == 1 & session == \"1\" ')\n",
Why ?

2020-11-20 10:10 UTC, lkorczowski commented on notebooks/data/data_info_duo.csv
> +2TL07_nuit_1.edf;2TL07;1;control;1;1;1;1;0;1;1;1;1;Beware MEMA channels names;1;1;;;;;;;[0,4];[1,5];8000;;;;;;;;group2
having two files with different format and almost all the same values is not recommended at all.
If you have issues updating data_info,
please change your regional settings in excel or use another software that manage ","
https://www.codeur.com/blog/alternatives-gratuites-excel/

2020-11-20 10:10 UTC, lkorczowski commented on notebooks/Middle_ear_Inter_subject_analysis.ipynb
> +    "data_info = pd.read_csv(info_file, sep=\";\").query('mema == 1 & included == 1 & session == \"1\" ')\n",
@RobinGuillard : this is the kind of thing that is almost impossible to catch without reviewNB when github refuse to load diff ;)

2020-11-20 10:10 UTC, lkorczowski commented on notebooks/Middle_ear_Inter_subject_analysis.ipynb
> +    "info_file = \"data/data_info_duo.csv\""
bad idea to have multiple files with overlapping data, please reverb back to data_info.

2020-11-20 10:10 UTC, lkorczowski commented on compute_results.py
> +                            results_MEMA[file] = reporting(epochs_MEMA[:,:1,:], valid_labels_MEMA, THR_classif_MEMA,
`epochs_MEMA[:,0,:]`instead ?

2020-11-20 10:10 UTC, lkorczowski commented on compute_results.py
> +                            results_MEMA[file + "_left"] = reporting(epochs_MEMA[:,1:,:], valid_labels_MEMA, THR_classif_MEMA,
`epochs_MEMA[:,1,:]`instead ?

2020-11-20 10:10 UTC, lkorczowski commented on compute_results.py
> +                                                           sleep_labels=sleep_labels_MEMA)
I think it is best to have something like:
```
results_MEMA[file] = ... #use both by default
if right_channel_exists:
    if (has_mask_pressure + has_press_diff) == 2:
        results_MEMA[file + "_right"] = ... #use right if exist (just copy/past results_MEMA[file]  if right is the only channel, no need to recompute)
    else:
        results_MEMA[file + "_right"] = results_MEMA[file]
if left_channel_exists:
    if (has_mask_pressure + has_press_diff) == 2:
        results_MEMA[file + "_left"] = ... #use left if exist  (just copy/past results_MEMA[file]  if right is the only channel, no need to recompute)
    else:
        results_MEMA[file + "_left"] = results_MEMA[file]
```
avantages:
- more reliable, no need to recompute the results if only one channel exist 
- much more compact

2020-11-20 10:10 UTC, lkorczowski commented on compute_results.py
> +                                                           sleep_labels=sleep_labels_MEMA)
nice !

Unfortunately, we will miss the both analysis but that's okay.

2020-11-20 13:56 UTC, RobinGuillard commented on compute_results.py
> +                            results_MEMA[file] = reporting(epochs_MEMA[:,:1,:], valid_labels_MEMA, THR_classif_MEMA,
No : if we do your line, it will collapse the 3 dimensions into 2. I have tried, doesn't work, it's important to leave it that way.

2020-11-20 13:57 UTC, RobinGuillard commented on compute_results.py
> +                            results_MEMA[file + "_left"] = reporting(epochs_MEMA[:,1:,:], valid_labels_MEMA, THR_classif_MEMA,
nope

2020-11-20 14:08 UTC, RobinGuillard commented on compute_results.py
> +                                                           sleep_labels=sleep_labels_MEMA)
I think you shouldn't create a "left" or "right" tag if it's the only channel you have, as it will make the sorting of good recordings harder for the laterality tests. We should hence write the following code:
```
results_MEMA[file] = ... #use both if avalaible, or left or right if it's the only option ("as many as we can" choice)
if (has_mask_pressure + has_press_diff) == 2:
        results_MEMA[file + "_right"] = ... #use right if exist (just copy/past results_MEMA[file]  if right is the only channel, no need to recompute)
        results_MEMA[file + "_left"] = ... #use left if exist  (just copy/past results_MEMA[file]  if right is the only channel, no need to recompute)
```
avantages:
- less space in memory
- even more compact
Cons : 
- in the MEMA analysis on all files, we will be comparing hetergeneous data with left datas with right datas with both datas "the best we have from a recording", but it's only a slightproblem

2020-11-24 13:05 UTC, lkorczowski approved these changes
OK, so I started to clean the NB but it takes actually a too much time. So... anyway. Approved.

2020-11-24 13:05 UTC, lkorczowski commented on compute_results.py
> +                            or file == "2TL07_nuit_1.edf":
we should use data_info instead

2020-11-24 13:07 UTC, lkorczowski commented
@RobinGuillard merge when you want but please read my recommendations for good practices 
- not using hard-coded variables in NB such as users (use instead data_info.csv which has the advantage for being shared across NB).  
- use readable output in NB

2020-11-24 13:41 UTC, merged