Sleep reporting
lkorczowski/Tinnitus-n-Sleep pull request #98
Opened 2020-07-24 10:53 UTC by lkorczowski

- [x] massive overhaul of `reports` and `test_reports`. Fix several (small) issues that wasn't spotted which could have modified the results silently if bad parameters where given
- [x] add full management of sleep labels:
- [x] general purpose `label_report()` function in utils for simple yet massive time saving when needed of reporting many variables (could be extended, and replace all the manual addition in `reporting()` ).
- [x] general purpose `resample_labels()` in `utils` which is very potent to re-align ANY labels with ANY epochs given the timestamps of each. Extensively used to aligns sleep labels.

update
-------
- [x] add auto-generated sleep labels
- [x] add sleep labels comparison
- [x] generate report for matching between noxturnal and Maxime's labels
- [x] generate report for matching between noxturnal and Paul's algorithm

2020-07-29 09:34 UTC, RobinGuillard requested changes
Stop killing notebooks, they want to live.

2020-07-29 09:34 UTC, RobinGuillard commented on compute_results.py
> +                        print(f"WARNING delta_start {delta_start}", end=" ")
Not clear what deltastart contains... commenting your code would help!

2020-07-29 09:34 UTC, RobinGuillard commented on tinnsleep/utils.py
> +def resample_labels(labels, xnew, x=None, kind='previous'):
Why "kind" have a default value at "previous" whereas in merge_labels_list it is nearest? it doesn't seem logical, better change it for nearest?

2020-07-29 09:34 UTC, RobinGuillard commented on tinnsleep/utils.py
> +    By default, the labels are associated with the previous
Sentence not ended?

2020-07-29 09:34 UTC, RobinGuillard commented on tinnsleep/utils.py
> +        x = range(len(labels))
x=1?

2020-07-29 09:34 UTC, RobinGuillard commented on tinnsleep/utils.py
> +def merge_label_and_events(events_time, labels, time_interval):
Docstring missing

2020-07-29 09:34 UTC, RobinGuillard commented on tinnsleep/utils.py
> +def label_report(labels):
Docstring missing

2020-07-29 09:34 UTC, RobinGuillard commented on tests/test_utils.py
> +    npt.assert_equal(v_lab, [True, True, True, True, True, False, False, False, False])
how this test is necessary compared to the otheer one just above?

2020-07-29 09:34 UTC, RobinGuillard commented on tests/test_utils.py
> +    npt.assert_equal(resample_labels(labels, [-2, -10, 1000], [-20, -5, 20, 1500, 10000], kind='nearest'), ["B", "B", "D"])
Ok now I see why you made the "previous" default argument instead of nearest, yet it would still seem more logical let "nearest be the default value and here test with kind="previous"

2020-07-29 09:34 UTC, RobinGuillard commented on tests/test_utils.py
> +    npt.assert_equal(report, report_expected)
I really prefer when you write explicitly the report awaited, because here maybe you have two similar mistakes that pass the test

2020-07-29 09:48 UTC, lkorczowski commented on tinnsleep/utils.py
> +def resample_labels(labels, xnew, x=None, kind='previous'):
`merge_labels_list` has not the same goal than `resample_labels` that why both strategies are different. 
The first one merge several list of labels, than taking the nearest is the best option.
`resample_labels` on the opposite will benefit from taking 'previous' as the last label is taking (and this labels won't be merged with many other lists)

2020-09-21 07:54 UTC, lkorczowski commented on tinnsleep/utils.py
> +    By default, the labels are associated with the previous
done

2020-09-28 09:16 UTC, lkorczowski commented on tests/test_utils.py
> +    npt.assert_equal(report, report_expected)
done

2020-09-28 09:21 UTC, lkorczowski commented on tests/test_utils.py
> +    npt.assert_equal(v_lab, [True, True, True, True, True, False, False, False, False])
it is not. it is independent.

2020-09-28 11:35 UTC, lkorczowski commented on tinnsleep/utils.py
> +def merge_label_and_events(events_time, labels, time_interval):
done

2020-10-11 13:19 UTC, lkorczowski commented
@RobinGuillard : are we ready to merge ?

2020-10-20 18:36 UTC, RobinGuillard approved these changes
Parameters for MEMA analysis of end august 15 patients seems good to me.

I trust for now your work on sleep labels, I should devote more time to check it but tonight it's a little challenging ^^
I approuve that you continue for the next sprint on MEMA analysis on 15 end of august patients

2020-10-20 18:36 UTC, RobinGuillard commented on compute_results.py
> +                        raw.rename_channels({'Mask Pressure': 'Airflow', "Pression diff": 'Airflow (L)'})
Ok why not : but currently no analysis is done on "aiflow (L)", we should consider maybe at some point making two analyses for the 2 MEMA channel starting this point.

2020-10-20 18:36 UTC, RobinGuillard commented on compute_results.py
> +
Would be better with more code annotation

2020-10-20 18:36 UTC, RobinGuillard commented on notebooks/check_annotations.py
> +    data_info = pd.read_csv("data/data_info.csv", engine='python', sep=";")
Curious : not data_info2?

2020-10-21 08:31 UTC, lkorczowski commented on notebooks/check_annotations.py
> +    data_info = pd.read_csv("data/data_info.csv", engine='python', sep=";")
data_info2 was temporary (for not breaking the code). 
Good point however, I need to double check that all instances of data_info2.csv are removed

2020-10-22 14:55 UTC, lkorczowski commented on notebooks/check_annotations.py
> +    data_info = pd.read_csv("data/data_info.csv", engine='python', sep=";")
done, not data_info2 used in the last version.

2020-10-22 15:00 UTC, lkorczowski commented on compute_results.py
> +
done

2020-10-22 15:00 UTC, lkorczowski commented on compute_results.py
> +                        raw.rename_channels({'Mask Pressure': 'Airflow', "Pression diff": 'Airflow (L)'})
please add it to the sprint's backlog if needed.

2020-10-22 15:04 UTC, merged